name: JSON Validation

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to validate from the caller workflow'
        default: 'main'
        required: false
        type: string

jobs:
  json-validate-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the chosen branch to STDOUT
      - run: echo ${{ inputs.branch }}
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - run: echo "checkout done"
      - name: Do validation
        id: validation
        uses: lyubick/action-YAML-schema-validator@v3
        with:
          json-schema-file: ./validation/schema.json
          yaml-json-file-dir: ./data
