name: main
on: [push]
jobs:
  json-validate-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "validation done"
      - name: Do validation
        uses: lyubick/action-YAML-schema-validator@v2
        with:
          json-schema-file: validation/schema.json
          yaml-json-file-dir: data
          recursive: true
