name: main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  json-validate-job:
    name: JSON Validation
    uses: ./.github/workflows/json-validation.yml
    secrets: inherit
